#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset fp+ /usr/share/fonts/local
xset fp rehash
# setxkbmap dvorak

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
source $HOME/.xsessionrc
$HOME/bin/xmonad.autostart &

exec ck-launch-session xmonad
#exec /usr/bin/openbox

